#SPDX-License-Identifier: MIT-0
---
# tasks file for grafana

# 1. sudo apt-get install -y apt-transport-https software-properties-common wget
- name: Install required packages
  ansible.builtin.package:
    name:
      - apt-transport-https
      - software-properties-common
      - wget
      - acl
    state: present

# 2. Create folder | sudo mkdir -p /etc/apt/keyrings/
- name: Create folder /etc/apt/keyrings
  ansible.builtin.file:
    path: /etc/apt/keyrings
    recurse: true

# 3. wget -q -O https://apt/grafana.com/gpg.key
#    | gpg --dearmor |
#    sudo tee /etc/apt/keyrings/grafana.gpg  > /dev/null
- name: Add Grafana APT key
  ansible.builtin.apt_key:
    url: https://apt.grafana.com/gpg.key
    keyring: /etc/apt/keyrings/grafana.gpg

- name: Add specified repository into sources List
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main
    state: present

- name: Update all package all packages to their latest version
  ansible.builtin.apt:
    name : "*"
    state: latest
    cache_valid_time: 3600
  
# sudo apt-get update-grafana
- name: Install Grafana on server
  ansible.builtin.apt:
    name: grafana
    state: present

# sudo systemctl daemon-reload
- name: Reload daemons
  ansible.builtin.systemd_service:
    name: grafana-server
    daemon_reload: true
    state: started

- name: Display how to connect to the grafana server instance
  ansible.builtin.debug:
    msg: "Connect at http://{{ external_ip }}:3000"