#SPDX-License-Identifier: MIT-0
---
# tasks file for promtail
- name: Install required packages
  ansible.builtin.package:
    name:
      - unzip
      - tar
      - gzip
      - bzip2
    state: present
    
- name: Download Promtail
  ansible.builtin.get_url:
    url: https://github.com/grafana/loki/releases/download/v2.9.7/promtail-linux-amd64.zip
    dest: /tmp/promtail.zip

- name: Unzip Promtail
  ansible.builtin.unarchive:
    src: /tmp/promtail.zip
    dest: /usr/local/bin/
    remote_src: yes

- name: Make Promtail executable
  ansible.builtin.file:
    path: /usr/local/bin/promtail-linux-amd64
    mode: '0755'

- name: Create Promtail config
  ansible.builtin.copy:
    dest: /etc/promtail/promtail-config.yaml
    content: |
      server:
        http_listen_port: 9080
        grpc_listen_port: 0

      positions:
        filename: /tmp/positions.yaml

      clients:
        - url: http://localhost:3100/loki/api/v1/push

      scrape_configs:
        - job_name: system
          static_configs:
            - targets:
                - localhost
              labels:
                job: varlogs
                __path__: /var/log/*log

- name: Create Promtail service
  ansible.builtin.copy:
    dest: /etc/systemd/system/promtail.service
    content: |
      [Unit]
      Description=Promtail
      After=network.target

      [Service]
      ExecStart=/usr/local/bin/promtail-linux-amd64 -config.file=/etc/promtail/promtail-config.yaml

      [Install]
      WantedBy=multi-user.target

- name: Start Promtail
  ansible.builtin.systemd:
    name: promtail
    enabled: yes
    state: started