---
- name: Install required packages
  ansible.builtin.package:
    name:
      - tar
      - gzip
    state: present

- name: Download Prometheus
  ansible.builtin.get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.52.0/prometheus-2.52.0.linux-amd64.tar.gz
    dest: /tmp/prometheus.tar.gz

- name: Extract Prometheus
  ansible.builtin.unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /opt/
    remote_src: yes

- name: Create Prometheus binary symlink
  ansible.builtin.file:
    src: /opt/prometheus-2.52.0.linux-amd64/prometheus
    dest: /usr/local/bin/prometheus
    state: link
    force: yes

- name: Create Prometheus data directory
  ansible.builtin.file:
    path: /opt/prometheus-2.52.0.linux-amd64/data
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Ensure Prometheus directory ownership
  ansible.builtin.file:
    path: /opt/prometheus-2.52.0.linux-amd64
    state: directory
    owner: root
    group: root
    recurse: yes
    mode: '0755'

- name: Create Prometheus configuration file
  ansible.builtin.copy:
    dest: /opt/prometheus-2.52.0.linux-amd64/prometheus.yml
    content: |
      global:
        scrape_interval: 15s

      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets: ['localhost:9090']
    mode: '0644'

- name: Create Prometheus systemd service
  ansible.builtin.copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus
      After=network.target

      [Service]
      ExecStart=/usr/local/bin/prometheus --config.file=/opt/prometheus-2.52.0.linux-amd64/prometheus.yml --storage.tsdb.path=/opt/prometheus-2.52.0.linux-amd64/data
      Restart=always
      User=root

      [Install]
      WantedBy=multi-user.target
    mode: '0644'

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Start and enable Prometheus
  ansible.builtin.systemd:
    name: prometheus
    enabled: yes
    state: started
